spring.application.name=db-api
spring.datasource.url=jdbc:postgresql://localhost:5432/zepto-db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update